build_from:
  armhf: "ghcr.io/home-assistant/armhf-base-python:latest"
  armv7: "ghcr.io/home-assistant/armv7-base-python:latest"
  aarch64: "ghcr.io/home-assistant/aarch64-base-python:latest"
  amd64: "ghcr.io/home-assistant/amd64-base-python:latest"
  i386: "ghcr.io/home-assistant/i386-base-python:latest"
